#:kivy 2.3
<Button>
    size_hint: 0.2, 0.2
    font_size: 32
<CalcLayout>

    BoxLayout:
        orientation: 'vertical'
        size: root.width, root.height
        padding: 5
        

        TextInput:
            id: calc_input
            text: '0'
            halign: 'right'
            font_size: 65
            size_hint: 1, 0.2
            background_color: 0.10, 0.10, 0.15, 1
            foreground_color: 1, 1, 1, 1
        
        GridLayout:
            cols: 4
            rows: 5
            spacing: 5

            # Row1
            Button:
                text: '%'
                background_color: 0.40, 0.40, 0.50, 1
                on_press: root.digit(self)
            Button:
                text: 'CE'
                background_color: 0.40, 0.40, 0.50, 1
                on_press: root.clear()
            Button:
                id: clear
                text: 'C'
                background_color: 0.40, 0.40, 0.50, 1
                on_press: root.clear()
            Button:
                text: '÷'
                background_color: 0.40, 0.40, 0.50, 1
                on_press: root.digit(self)

            # Row2
            Button:
                text: '7'
                on_press: root.digit(self)
            Button:
                text: '8'
                on_press: root.digit(self)
            Button:
                text: '9'
                on_press: root.digit(self)
            Button:
                text: '*'
                background_color: 0.40, 0.40, 0.50, 1
                on_press: root.digit(self)

            # Row3
            Button:
                text: '4'
                on_press: root.digit(self)
            Button:
                text: '5'
                on_press: root.digit(self)
            Button:
                text: '6'
                on_press: root.digit(self)
            Button:
                text: '-'
                background_color: 0.40, 0.40, 0.50, 1
                on_press: root.digit(self)

            # Row4
            Button:
                text: '1'
                on_press: root.digit(self)
            Button:
                text: '2'
                on_press: root.digit(self)
            Button:
                text: '3'
                on_press: root.digit(self)
            Button:
                text: '+'
                background_color: 0.40, 0.40, 0.50, 1
                on_press: root.digit(self)

            # Row5
            Button:
                text: '+/-'
                on_press: root.change_sign()
            Button:
                text: '0'
                on_press: root.digit(self)
            Button:
                text: '.'
                on_press: root.digit(self)
            Button:
                text: '='
                background_color: 0.40, 0.40, 0.80, 1
                on_press: root.equals_buttom_pressed()